// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZySflRDzNxnjBTHxwaPtAUNXrGeLgWg',
    appId: '1:885643133158:web:09af519e2cb69b8120bb27',
    messagingSenderId: '885643133158',
    projectId: 'webchat-29cd1',
    authDomain: 'webchat-29cd1.firebaseapp.com',
    storageBucket: 'webchat-29cd1.appspot.com',
    measurementId: 'G-DYMTLQZDPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVVfUMEZiBigx_wZ6dmmtcrXDeG3Eibk',
    appId: '1:885643133158:android:3dbe7e5863a6364b20bb27',
    messagingSenderId: '885643133158',
    projectId: 'webchat-29cd1',
    storageBucket: 'webchat-29cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_0JE927umhUnaqGfoHAV3G_oArSMFF8',
    appId: '1:885643133158:ios:bcefe72ce41a6c4b20bb27',
    messagingSenderId: '885643133158',
    projectId: 'webchat-29cd1',
    storageBucket: 'webchat-29cd1.appspot.com',
    iosBundleId: 'com.example.webchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_0JE927umhUnaqGfoHAV3G_oArSMFF8',
    appId: '1:885643133158:ios:bcefe72ce41a6c4b20bb27',
    messagingSenderId: '885643133158',
    projectId: 'webchat-29cd1',
    storageBucket: 'webchat-29cd1.appspot.com',
    iosBundleId: 'com.example.webchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVZySflRDzNxnjBTHxwaPtAUNXrGeLgWg',
    appId: '1:885643133158:web:83a7ea7e258cf1ac20bb27',
    messagingSenderId: '885643133158',
    projectId: 'webchat-29cd1',
    authDomain: 'webchat-29cd1.firebaseapp.com',
    storageBucket: 'webchat-29cd1.appspot.com',
    measurementId: 'G-CD3P6FN77M',
  );
}
